# Generated by Django 4.2 on 2024-04-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(default=dict)),
                ('visit_date', models.DateTimeField(blank=True, null=True)),
                ('class_sections', models.ManyToManyField(to='cis.classsection')),
                ('visitors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(default=dict)),
                ('teacher_discussion', models.TextField()),
                ('student_discussion', models.TextField()),
                ('visit_letter', models.TextField()),
                ('status', models.CharField(choices=[('', '---'), ('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft', max_length=10)),
                ('payment_processed', models.CharField(choices=[('', 'Select'), ('1', 'Yes'), ('2', 'No')], max_length=10)),
                ('visit_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_visit.visitschedule')),
            ],
        ),
    ]
