# Generated by Django 4.2 on 2025-08-08 15:25

import cis.storage_backend
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('class_visit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitReportFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=cis.storage_backend.PrivateMediaStorage(), upload_to='visit_report_files/')),
                ('visit_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='class_visit.visitreport')),
            ],
        ),
    ]
