# Generated by Django 5.2.15 on 2026-06-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_visit', '0002_visitreportfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitschedule',
            name='type_of_visit',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
