# Generated by Django 5.2.15 on 2026-06-15 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_visit', '0004_dedup_visit_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitreport',
            name='visit_schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='class_visit.visitschedule'),
        ),
    ]
