# Generated by Django 5.2.15 on 2026-06-15 23:35

from django.db import migrations


OLD_KEY = 'cis.settings.class_visit_emails'
NEW_KEY = 'class_visit'

FIELD_MAP = {
    # old_field_name: new_field_name
    'is_active': 'is_active',
    'debug_email_list': 'debug_email_list',
    'instructor_visit_scheduled_subject': 'teacher_scheduled_subject',
    'instructor_visit_scheduled_email': 'teacher_scheduled_message',
    'visitor_visit_scheduled_subject': 'visitor_reminder_subject',
    'visitor_visit_scheduled_email': 'visitor_reminder_message',
    'instructor_visit_letter_subject': 'teacher_submit_subject',
    'visit_report_submitted_subject': 'teacher_submit_subject',  # may overwrite above; last wins
    'visit_report_submitted_email': 'teacher_submit_message',
}

DEFAULT_NEW_VALUES = {
    'report_fields_json': '[]',
    'visit_types': 'Initial|Follow-up|Annual',
    'section_status_filter': 'active',
    'notify_target': 'course_administrator',
    'generic_email': '',
    'notify_teacher_on_schedule': 'No',
    'instructor_confirm_link': 'No',
    'notify_teacher_on_submit': 'No',
    'teacher_submit_message': '',
    'visitor_reminder_message': '',
    'reminder_every_days': 7,
}


def migrate_settings(apps, schema_editor):
    Setting = apps.get_model('cis', 'Setting')

    # Load old values (may not exist on fresh installs)
    old_values = {}
    try:
        old_setting = Setting.objects.get(key=OLD_KEY)
        old_values = old_setting.value or {}
    except Setting.DoesNotExist:
        pass

    # Build new values: start with defaults, then overwrite with mapped old values
    new_values = dict(DEFAULT_NEW_VALUES)
    for old_field, new_field in FIELD_MAP.items():
        if old_field in old_values:
            new_values[new_field] = old_values[old_field]

    # Create or update the new Setting row
    try:
        new_setting = Setting.objects.get(key=NEW_KEY)
        # Merge: only fill in missing keys so we don't overwrite an existing install
        existing = new_setting.value or {}
        for k, v in new_values.items():
            if k not in existing:
                existing[k] = v
        new_setting.value = existing
    except Setting.DoesNotExist:
        new_setting = Setting()
        new_setting.key = NEW_KEY
        new_setting.value = new_values

    new_setting.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('class_visit', '0006_add_notneededvisit'),
        ('cis', '__first__'),
    ]

    operations = [
        migrations.RunPython(migrate_settings, noop),
    ]
