# Generated by Django 5.2.17 on 2026-09-16 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_visit', '0008_add_class_visit_menu_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='instructor_responded_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='instructor_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='instructor_signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='instructor_signed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitreportfile',
            name='kind',
            field=models.CharField(choices=[('faculty_attachment', 'Visitor attachment'), ('instructor_response', 'Instructor response')], default='faculty_attachment', max_length=32),
        ),
        migrations.AddField(
            model_name='visitreportfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
